**The ML model role is to predict which individuals are most likely to have or use a bank account.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Financial_inclusion_dataset.csv')

In [3]:
#!pip install ydata-profiling
import pandas as pd
#import ydata_profiling

#profile = ydata_profiling.ProfileReport(df)
#profile.to_file("output.html")


In [4]:
#from IPython.display import HTML

# Load the HTML report
#with open("output.html") as f:
    #report_html = f.read()

# Display the report in the notebook
#display(HTML(report_html))

In [5]:
df.head()

country  year    uniqueid bank_account location_type cellphone_access  \
0   Kenya  2018  uniqueid_1          Yes         Rural              Yes   
1   Kenya  2018  uniqueid_2           No         Rural               No   
2   Kenya  2018  uniqueid_3          Yes         Urban              Yes   
3   Kenya  2018  uniqueid_4           No         Rural              Yes   
4   Kenya  2018  uniqueid_5           No         Urban               No   

   household_size  age_of_respondent gender_of_respondent  \
0               3                 24               Female   
1               5                 70               Female   
2               5                 26                 Male   
3               5                 34               Female   
4               8                 26                 Male   

  relationship_with_head           marital_status  \
0                 Spouse  Married/Living together   
1      Head of Household                  Widowed   
2         Other relative     Single/Never Married   
3      Head of Household  Married/Living together   
4                  Child     Single/Never Married   

                   education_level                   job_type  
0              Secondary education              Self employed  
1              No formal education       Government Dependent  
2  Vocational/Specialised training              Self employed  
3                Primary education  Formally employed Private  
4                Primary education        Informally employed

In [6]:
df.drop(columns=['uniqueid'], inplace=True)
df.head()


country  year bank_account location_type cellphone_access  household_size  \
0   Kenya  2018          Yes         Rural              Yes               3   
1   Kenya  2018           No         Rural               No               5   
2   Kenya  2018          Yes         Urban              Yes               5   
3   Kenya  2018           No         Rural              Yes               5   
4   Kenya  2018           No         Urban               No               8   

   age_of_respondent gender_of_respondent relationship_with_head  \
0                 24               Female                 Spouse   
1                 70               Female      Head of Household   
2                 26                 Male         Other relative   
3                 34               Female      Head of Household   
4                 26                 Male                  Child   

            marital_status                  education_level  \
0  Married/Living together              Secondary education   
1                  Widowed              No formal education   
2     Single/Never Married  Vocational/Specialised training   
3  Married/Living together                Primary education   
4     Single/Never Married                Primary education   

                    job_type  
0              Self employed  
1       Government Dependent  
2              Self employed  
3  Formally employed Private  
4        Informally employed

In [7]:
df.year.unique()

array([2018, 2016, 2017], dtype=int64)

In [8]:
from sklearn.preprocessing import LabelEncoder
Country = LabelEncoder()
df['country'] = Country.fit_transform(df['country'])
df["country"].unique()
Location = LabelEncoder()
df['location_type'] = Location.fit_transform(df['location_type'])
df["location_type"].unique()
cell = LabelEncoder()
df['cellphone_access'] = cell.fit_transform(df['cellphone_access'])
df["cellphone_access"].unique()
gender = LabelEncoder()
df['gender_of_respondent'] = gender.fit_transform(df['gender_of_respondent'])
df["gender_of_respondent"].unique()
relation = LabelEncoder()
df['relationship_with_head'] = relation.fit_transform(df['relationship_with_head'])
df["relationship_with_head"].unique()
marital = LabelEncoder()
df['marital_status'] = marital.fit_transform(df['marital_status'])
df["marital_status"].unique()
education = LabelEncoder()
df['education_level'] = education.fit_transform(df['education_level'])
df["education_level"].unique()
job = LabelEncoder()
df['job_type'] = job.fit_transform(df['job_type'])
df["job_type"].unique()




array([9, 4, 3, 5, 2, 1, 8, 7, 0, 6])

In [9]:
bank = LabelEncoder()
df['bank_account'] = bank.fit_transform(df['bank_account'])
df["bank_account"].unique()

array([1, 0])

In [10]:
df.head()

country  year  bank_account  location_type  cellphone_access  \
0        0  2018             1              0                 1   
1        0  2018             0              0                 0   
2        0  2018             1              1                 1   
3        0  2018             0              0                 1   
4        0  2018             0              1                 0   

   household_size  age_of_respondent  gender_of_respondent  \
0               3                 24                     0   
1               5                 70                     0   
2               5                 26                     1   
3               5                 34                     0   
4               8                 26                     1   

   relationship_with_head  marital_status  education_level  job_type  
0                       5               2                3         9  
1                       1               4                0         4  
2                       3               3                5         9  
3                       1               2                2         3  
4                       0               3                2         5

In [11]:
X = df.drop('bank_account', axis=1)
y = df.bank_account

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.1, random_state=1234)


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize the Logistic Regression Classifier
clf = LogisticRegression(random_state=42)

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.8674033149171271


c:\Users\AUVIGHA TECH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
import pickle


In [15]:
data = {"model": clf, "Country": Country, "Location": Location,'cell':cell,'gender':gender,'relation':relation,'marital':marital,'education':education,'job':job}
with open('bank_account.pkl', 'wb') as file:
    pickle.dump(data, file)

In [16]:
with open('bank_account.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
Country = data["Country"]
Location = data["Location"]
cell = data["cell"]
gender = data["gender"]
relation = data["relation"]
marital = data["marital"]
education = data["education"]
job = data["job"]


In [17]:
data = [["Kenya", 2018,  "Rural", "Yes", 3, 24, "Female", "Spouse", "Married/Living together", "Secondary education", "Self employed"]]


In [18]:
data_np = np.array(data)
print(data_np)

[['Kenya' '2018' 'Rural' 'Yes' '3' '24' 'Female' 'Spouse'
  'Married/Living together' 'Secondary education' 'Self employed']]


In [19]:
print(data_np.shape)

(1, 11)


In [20]:
data_np[:, 0] = Country.transform(data_np[:,0])
data_np[:, 2] = Location.transform(data_np[:,2])
data_np[:, 3] = cell.transform(data_np[:,3])
data_np[:, 6] = gender.transform(data_np[:,6])
data_np[:, 7] = relation.transform(data_np[:,7])
data_np[:, 8] = marital.transform(data_np[:,8])
data_np[:, 9] = education.transform(data_np[:,9])
data_np[:, 10] = job.transform(data_np[:,10])




data_np

array([['0', '2018', '0', '1', '3', '24', '0', '5', '2', '3', '9']],
      dtype='<U23')

In [21]:
data_np=data_np.astype(float)
data_np

array([[0.000e+00, 2.018e+03, 0.000e+00, 1.000e+00, 3.000e+00, 2.400e+01,
        0.000e+00, 5.000e+00, 2.000e+00, 3.000e+00, 9.000e+00]])

In [22]:
y_pred = regressor_loaded.predict(data_np)
y_pred

c:\Users\AUVIGHA TECH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])